import { bindings } from "./bindings.server";

const COOKIE="bdh_admin_session";
const SESSION_DAYS=7;
const CODE_MINUTES=10;
const VERIFIED_MINUTES=15;
const PBKDF2_ITERATIONS=210000;
const CODE_COOLDOWN_MS=60000;
type AdminRow={id:string;email:string;password_hash:string};
function database(){const {DB}=bindings();if(!DB)throw new Error("Database is not configured");return DB;}
async function sha256(value:string){const buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(buf),b=>b.toString(16).padStart(2,"0")).join("");}
function constantTimeHexEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function derive(password:string,saltHex:string,iterations:number){const salt=Uint8Array.from((saltHex.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations,hash:"SHA-256"},material,256);return Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,"0")).join("");}
async function hashPassword(password:string){const saltBytes=new Uint8Array(16);crypto.getRandomValues(saltBytes);const salt=Array.from(saltBytes,b=>b.toString(16).padStart(2,"0")).join("");return "pbkdf2$"+PBKDF2_ITERATIONS+"$"+salt+"$"+await derive(password,salt,PBKDF2_ITERATIONS);}
async function verifyPassword(password:string,stored:string){const parts=stored.split("$");if(parts.length!==4||parts[0]!=="pbkdf2")return false;const iterations=Number(parts[1]);if(!Number.isFinite(iterations)||iterations<100000||iterations>500000||!/^[a-f0-9]{32}$/.test(parts[2])||!/^[a-f0-9]{64}$/.test(parts[3]))return false;return constantTimeHexEqual(await derive(password,parts[2],iterations),parts[3]);}
function now(){return new Date().toISOString();}
function code6(){const x=new Uint32Array(1);crypto.getRandomValues(x);return String(x[0]%1000000).padStart(6,"0");}
function sessionCookie(token:string,maxAge:number){return COOKIE+"="+encodeURIComponent(token)+"; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age="+maxAge;}
export function loginCookie(token:string){return sessionCookie(token,SESSION_DAYS*86400);}
export function clearLoginCookie(){return sessionCookie("",0);}
export function parseCookie(request:Request){const raw=request.headers.get("cookie")||"";for(const piece of raw.split(";")){const parts=piece.trim().split("=");const key=parts.shift();if(key===COOKIE)return decodeURIComponent(parts.join("="));}return null;}
export function sameOrigin(request:Request){const origin=request.headers.get("origin");return !origin||origin===new URL(request.url).origin;}
async function configuredAdmin(){const env=bindings() as Record<string,unknown>;return{email:typeof env.ADMIN_EMAIL==="string"?env.ADMIN_EMAIL.trim().toLowerCase():"",password:typeof env.ADMIN_INITIAL_PASSWORD==="string"?env.ADMIN_INITIAL_PASSWORD:""};}
export async function ensureAdminSeeded(){const db=database();const found=await db.prepare("SELECT id FROM admin_users LIMIT 1").first<{id:string}>();if(found)return true;const configured=await configuredAdmin();if(!/^[^@\s]+@gmail\.com$/i.test(configured.email)||configured.password.length<10)return false;await db.prepare("INSERT OR IGNORE INTO admin_users(id,email,password_hash) VALUES(?,?,?)").bind(crypto.randomUUID(),configured.email,await hashPassword(configured.password)).run();return true;}
export async function authenticate(email:string,password:string){if(!(await ensureAdminSeeded()))return null;const admin=await database().prepare("SELECT id,email,password_hash FROM admin_users WHERE email=?").bind(email.trim().toLowerCase()).first<AdminRow>();if(!admin||!(await verifyPassword(password,admin.password_hash)))return null;return admin;}
export async function getAdmin(request:Request){const token=parseCookie(request);if(!token)return null;const hash=await sha256(token);return await database().prepare("SELECT u.id,u.email,u.password_hash FROM admin_sessions s JOIN admin_users u ON u.id=s.admin_id WHERE s.token_hash=? AND s.expires_at>datetime('now')").bind(hash).first<AdminRow>()??null;}
export async function createSession(adminId:string){const token=crypto.randomUUID()+"."+crypto.randomUUID();const hash=await sha256(token);const expiry=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await database().prepare("INSERT INTO admin_sessions(id,admin_id,token_hash,expires_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),adminId,hash,expiry).run();return token;}
export async function destroySession(request:Request){const token=parseCookie(request);if(!token)return;await database().prepare("DELETE FROM admin_sessions WHERE token_hash=?").bind(await sha256(token)).run();}
export async function isRateLimited(request:Request){const ip=request.headers.get("CF-Connecting-IP")||"unknown";const bucket=await sha256(ip);const row=await database().prepare("SELECT attempts,window_started_at FROM login_limits WHERE bucket=?").bind(bucket).first<{attempts:number;window_started_at:string}>();if(!row){await database().prepare("INSERT INTO login_limits(bucket,attempts,window_started_at) VALUES(?,?,?)").bind(bucket,0,now()).run();return false;}if(Date.now()-new Date(row.window_started_at).getTime()>900000){await database().prepare("UPDATE login_limits SET attempts=0,window_started_at=? WHERE bucket=?").bind(now(),bucket).run();return false;}return row.attempts>=8;}
export async function failedLogin(request:Request){const ip=request.headers.get("CF-Connecting-IP")||"unknown";await database().prepare("UPDATE login_limits SET attempts=attempts+1 WHERE bucket=?").bind(await sha256(ip)).run();}
async function canIssueCode(table:"password_codes"|"admin_email_change_codes",adminId:string){const row=await database().prepare("SELECT created_at FROM "+table+" WHERE admin_id=? ORDER BY created_at DESC LIMIT 1").bind(adminId).first<{created_at:string}>();return !row||Date.now()-new Date(row.created_at).getTime()>=CODE_COOLDOWN_MS;}
export async function issueCode(adminId:string){if(!(await canIssueCode("password_codes",adminId)))return null;const code=code6();await database().prepare("DELETE FROM password_codes WHERE admin_id=? OR expires_at<=datetime('now')").bind(adminId).run();await database().prepare("INSERT INTO password_codes(id,admin_id,code_hash,expires_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),adminId,await sha256(code),new Date(Date.now()+CODE_MINUTES*60000).toISOString()).run();return code;}
export async function verifyCode(adminId:string,code:string){const row=await database().prepare("SELECT id,code_hash,attempts,expires_at FROM password_codes WHERE admin_id=? AND verified_at IS NULL ORDER BY created_at DESC LIMIT 1").bind(adminId).first<{id:string;code_hash:string;attempts:number;expires_at:string}>();if(!row||row.attempts>=5||Date.now()>=new Date(row.expires_at).getTime())return false;const ok=constantTimeHexEqual(await sha256(code),row.code_hash);if(!ok)await database().prepare("UPDATE password_codes SET attempts=attempts+1 WHERE id=?").bind(row.id).run();else await database().prepare("UPDATE password_codes SET verified_at=? WHERE id=?").bind(now(),row.id).run();return ok;}
export async function changePassword(adminId:string,password:string){const row=await database().prepare("SELECT verified_at FROM password_codes WHERE admin_id=? AND verified_at IS NOT NULL ORDER BY verified_at DESC LIMIT 1").bind(adminId).first<{verified_at:string}>();if(!row||Date.now()-new Date(row.verified_at).getTime()>VERIFIED_MINUTES*60000)return false;await database().prepare("UPDATE admin_users SET password_hash=?,updated_at=? WHERE id=?").bind(await hashPassword(password),now(),adminId).run();await database().prepare("DELETE FROM password_codes WHERE admin_id=?").bind(adminId).run();await database().prepare("DELETE FROM admin_sessions WHERE admin_id=?").bind(adminId).run();return true;}
function validGmail(value:string){return /^[^@\s]+@gmail\.com$/i.test(value.trim());}
export async function issueEmailChangeCode(adminId:string,newEmail:string){const normalized=newEmail.trim().toLowerCase();if(!validGmail(normalized))return{code:null,error:"invalid_email" as const};const current=await database().prepare("SELECT email FROM admin_users WHERE id=?").bind(adminId).first<{email:string}>();if(!current)return{code:null,error:"unauthorized" as const};if(current.email.toLowerCase()===normalized)return{code:null,error:"same_email" as const};if(!(await canIssueCode("admin_email_change_codes",adminId)))return{code:null,error:"cooldown" as const};const code=code6();await database().prepare("DELETE FROM admin_email_change_codes WHERE admin_id=? OR expires_at<=datetime('now')").bind(adminId).run();await database().prepare("INSERT INTO admin_email_change_codes(id,admin_id,new_email,code_hash,attempts,expires_at) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),adminId,normalized,await sha256(code),0,new Date(Date.now()+CODE_MINUTES*60000).toISOString()).run();return{code,error:null};}
export async function verifyEmailChangeCode(adminId:string,code:string){const row=await database().prepare("SELECT id,code_hash,attempts,expires_at FROM admin_email_change_codes WHERE admin_id=? AND verified_at IS NULL ORDER BY created_at DESC LIMIT 1").bind(adminId).first<{id:string;code_hash:string;attempts:number;expires_at:string}>();if(!row||row.attempts>=5||Date.now()>=new Date(row.expires_at).getTime())return false;const ok=constantTimeHexEqual(await sha256(code),row.code_hash);if(!ok)await database().prepare("UPDATE admin_email_change_codes SET attempts=attempts+1 WHERE id=?").bind(row.id).run();else await database().prepare("UPDATE admin_email_change_codes SET verified_at=? WHERE id=?").bind(now(),row.id).run();return ok;}
export async function changeAdminEmail(adminId:string,newEmail:string){const normalized=newEmail.trim().toLowerCase();if(!validGmail(normalized))return false;const row=await database().prepare("SELECT new_email,verified_at FROM admin_email_change_codes WHERE admin_id=? AND verified_at IS NOT NULL ORDER BY verified_at DESC LIMIT 1").bind(adminId).first<{new_email:string;verified_at:string}>();if(!row||row.new_email!==normalized||Date.now()-new Date(row.verified_at).getTime()>VERIFIED_MINUTES*60000)return false;await database().prepare("UPDATE admin_users SET email=?,updated_at=? WHERE id=?").bind(normalized,now(),adminId).run();await database().prepare("DELETE FROM admin_email_change_codes WHERE admin_id=?").bind(adminId).run();await database().prepare("DELETE FROM admin_sessions WHERE admin_id=?").bind(adminId).run();return true;}
export const validPassword=(value:string)=>value.length>=10&&value.length<=128;
