/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiReviewImageRouteImport } from './routes/api/review-image'
import { Route as ApiMenuImageRouteImport } from './routes/api/menu-image'
import { Route as ApiMenuRouteImport } from './routes/api/menu'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiAdminReviewsRouteImport } from './routes/api/admin/reviews'
import { Route as ApiAdminReviewSettingsRouteImport } from './routes/api/admin/review-settings'
import { Route as ApiAdminReviewPhotoRouteImport } from './routes/api/admin/review-photo'
import { Route as ApiAdminPublishRouteImport } from './routes/api/admin/publish'
import { Route as ApiAdminPasswordVerifyCodeRouteImport } from './routes/api/admin/password-verify-code'
import { Route as ApiAdminPasswordRequestCodeRouteImport } from './routes/api/admin/password-request-code'
import { Route as ApiAdminPasswordChangeRouteImport } from './routes/api/admin/password-change'
import { Route as ApiAdminMenuPhotoRouteImport } from './routes/api/admin/menu-photo'
import { Route as ApiAdminMenuRouteImport } from './routes/api/admin/menu'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminEmailChangeVerifyCodeRouteImport } from './routes/api/admin/email-change-verify-code'
import { Route as ApiAdminEmailChangeRequestCodeRouteImport } from './routes/api/admin/email-change-request-code'
import { Route as ApiAdminEmailChangeRouteImport } from './routes/api/admin/email-change'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewImageRoute = ApiReviewImageRouteImport.update({
  id: '/api/review-image',
  path: '/api/review-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuImageRoute = ApiMenuImageRouteImport.update({
  id: '/api/menu-image',
  path: '/api/menu-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuRoute = ApiMenuRouteImport.update({
  id: '/api/menu',
  path: '/api/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReviewsRoute = ApiAdminReviewsRouteImport.update({
  id: '/api/admin/reviews',
  path: '/api/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReviewSettingsRoute = ApiAdminReviewSettingsRouteImport.update({
  id: '/api/admin/review-settings',
  path: '/api/admin/review-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReviewPhotoRoute = ApiAdminReviewPhotoRouteImport.update({
  id: '/api/admin/review-photo',
  path: '/api/admin/review-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPublishRoute = ApiAdminPublishRouteImport.update({
  id: '/api/admin/publish',
  path: '/api/admin/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPasswordVerifyCodeRoute =
  ApiAdminPasswordVerifyCodeRouteImport.update({
    id: '/api/admin/password-verify-code',
    path: '/api/admin/password-verify-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPasswordRequestCodeRoute =
  ApiAdminPasswordRequestCodeRouteImport.update({
    id: '/api/admin/password-request-code',
    path: '/api/admin/password-request-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPasswordChangeRoute = ApiAdminPasswordChangeRouteImport.update({
  id: '/api/admin/password-change',
  path: '/api/admin/password-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMenuPhotoRoute = ApiAdminMenuPhotoRouteImport.update({
  id: '/api/admin/menu-photo',
  path: '/api/admin/menu-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMenuRoute = ApiAdminMenuRouteImport.update({
  id: '/api/admin/menu',
  path: '/api/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailChangeVerifyCodeRoute =
  ApiAdminEmailChangeVerifyCodeRouteImport.update({
    id: '/api/admin/email-change-verify-code',
    path: '/api/admin/email-change-verify-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminEmailChangeRequestCodeRoute =
  ApiAdminEmailChangeRequestCodeRouteImport.update({
    id: '/api/admin/email-change-request-code',
    path: '/api/admin/email-change-request-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminEmailChangeRoute = ApiAdminEmailChangeRouteImport.update({
  id: '/api/admin/email-change',
  path: '/api/admin/email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/menu-image': typeof ApiMenuImageRoute
  '/api/review-image': typeof ApiReviewImageRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/email-change': typeof ApiAdminEmailChangeRoute
  '/api/admin/email-change-request-code': typeof ApiAdminEmailChangeRequestCodeRoute
  '/api/admin/email-change-verify-code': typeof ApiAdminEmailChangeVerifyCodeRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/menu': typeof ApiAdminMenuRoute
  '/api/admin/menu-photo': typeof ApiAdminMenuPhotoRoute
  '/api/admin/password-change': typeof ApiAdminPasswordChangeRoute
  '/api/admin/password-request-code': typeof ApiAdminPasswordRequestCodeRoute
  '/api/admin/password-verify-code': typeof ApiAdminPasswordVerifyCodeRoute
  '/api/admin/publish': typeof ApiAdminPublishRoute
  '/api/admin/review-photo': typeof ApiAdminReviewPhotoRoute
  '/api/admin/review-settings': typeof ApiAdminReviewSettingsRoute
  '/api/admin/reviews': typeof ApiAdminReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/menu-image': typeof ApiMenuImageRoute
  '/api/review-image': typeof ApiReviewImageRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/email-change': typeof ApiAdminEmailChangeRoute
  '/api/admin/email-change-request-code': typeof ApiAdminEmailChangeRequestCodeRoute
  '/api/admin/email-change-verify-code': typeof ApiAdminEmailChangeVerifyCodeRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/menu': typeof ApiAdminMenuRoute
  '/api/admin/menu-photo': typeof ApiAdminMenuPhotoRoute
  '/api/admin/password-change': typeof ApiAdminPasswordChangeRoute
  '/api/admin/password-request-code': typeof ApiAdminPasswordRequestCodeRoute
  '/api/admin/password-verify-code': typeof ApiAdminPasswordVerifyCodeRoute
  '/api/admin/publish': typeof ApiAdminPublishRoute
  '/api/admin/review-photo': typeof ApiAdminReviewPhotoRoute
  '/api/admin/review-settings': typeof ApiAdminReviewSettingsRoute
  '/api/admin/reviews': typeof ApiAdminReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/menu-image': typeof ApiMenuImageRoute
  '/api/review-image': typeof ApiReviewImageRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/email-change': typeof ApiAdminEmailChangeRoute
  '/api/admin/email-change-request-code': typeof ApiAdminEmailChangeRequestCodeRoute
  '/api/admin/email-change-verify-code': typeof ApiAdminEmailChangeVerifyCodeRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/menu': typeof ApiAdminMenuRoute
  '/api/admin/menu-photo': typeof ApiAdminMenuPhotoRoute
  '/api/admin/password-change': typeof ApiAdminPasswordChangeRoute
  '/api/admin/password-request-code': typeof ApiAdminPasswordRequestCodeRoute
  '/api/admin/password-verify-code': typeof ApiAdminPasswordVerifyCodeRoute
  '/api/admin/publish': typeof ApiAdminPublishRoute
  '/api/admin/review-photo': typeof ApiAdminReviewPhotoRoute
  '/api/admin/review-settings': typeof ApiAdminReviewSettingsRoute
  '/api/admin/reviews': typeof ApiAdminReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/bookings'
    | '/api/menu'
    | '/api/menu-image'
    | '/api/review-image'
    | '/api/reviews'
    | '/api/admin/bookings'
    | '/api/admin/email-change'
    | '/api/admin/email-change-request-code'
    | '/api/admin/email-change-verify-code'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/menu'
    | '/api/admin/menu-photo'
    | '/api/admin/password-change'
    | '/api/admin/password-request-code'
    | '/api/admin/password-verify-code'
    | '/api/admin/publish'
    | '/api/admin/review-photo'
    | '/api/admin/review-settings'
    | '/api/admin/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/bookings'
    | '/api/menu'
    | '/api/menu-image'
    | '/api/review-image'
    | '/api/reviews'
    | '/api/admin/bookings'
    | '/api/admin/email-change'
    | '/api/admin/email-change-request-code'
    | '/api/admin/email-change-verify-code'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/menu'
    | '/api/admin/menu-photo'
    | '/api/admin/password-change'
    | '/api/admin/password-request-code'
    | '/api/admin/password-verify-code'
    | '/api/admin/publish'
    | '/api/admin/review-photo'
    | '/api/admin/review-settings'
    | '/api/admin/reviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/bookings'
    | '/api/menu'
    | '/api/menu-image'
    | '/api/review-image'
    | '/api/reviews'
    | '/api/admin/bookings'
    | '/api/admin/email-change'
    | '/api/admin/email-change-request-code'
    | '/api/admin/email-change-verify-code'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/menu'
    | '/api/admin/menu-photo'
    | '/api/admin/password-change'
    | '/api/admin/password-request-code'
    | '/api/admin/password-verify-code'
    | '/api/admin/publish'
    | '/api/admin/review-photo'
    | '/api/admin/review-settings'
    | '/api/admin/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiMenuRoute: typeof ApiMenuRoute
  ApiMenuImageRoute: typeof ApiMenuImageRoute
  ApiReviewImageRoute: typeof ApiReviewImageRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRoute
  ApiAdminEmailChangeRoute: typeof ApiAdminEmailChangeRoute
  ApiAdminEmailChangeRequestCodeRoute: typeof ApiAdminEmailChangeRequestCodeRoute
  ApiAdminEmailChangeVerifyCodeRoute: typeof ApiAdminEmailChangeVerifyCodeRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminMenuRoute: typeof ApiAdminMenuRoute
  ApiAdminMenuPhotoRoute: typeof ApiAdminMenuPhotoRoute
  ApiAdminPasswordChangeRoute: typeof ApiAdminPasswordChangeRoute
  ApiAdminPasswordRequestCodeRoute: typeof ApiAdminPasswordRequestCodeRoute
  ApiAdminPasswordVerifyCodeRoute: typeof ApiAdminPasswordVerifyCodeRoute
  ApiAdminPublishRoute: typeof ApiAdminPublishRoute
  ApiAdminReviewPhotoRoute: typeof ApiAdminReviewPhotoRoute
  ApiAdminReviewSettingsRoute: typeof ApiAdminReviewSettingsRoute
  ApiAdminReviewsRoute: typeof ApiAdminReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-image': {
      id: '/api/review-image'
      path: '/api/review-image'
      fullPath: '/api/review-image'
      preLoaderRoute: typeof ApiReviewImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-image': {
      id: '/api/menu-image'
      path: '/api/menu-image'
      fullPath: '/api/menu-image'
      preLoaderRoute: typeof ApiMenuImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu': {
      id: '/api/menu'
      path: '/api/menu'
      fullPath: '/api/menu'
      preLoaderRoute: typeof ApiMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reviews': {
      id: '/api/admin/reviews'
      path: '/api/admin/reviews'
      fullPath: '/api/admin/reviews'
      preLoaderRoute: typeof ApiAdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/review-settings': {
      id: '/api/admin/review-settings'
      path: '/api/admin/review-settings'
      fullPath: '/api/admin/review-settings'
      preLoaderRoute: typeof ApiAdminReviewSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/review-photo': {
      id: '/api/admin/review-photo'
      path: '/api/admin/review-photo'
      fullPath: '/api/admin/review-photo'
      preLoaderRoute: typeof ApiAdminReviewPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/publish': {
      id: '/api/admin/publish'
      path: '/api/admin/publish'
      fullPath: '/api/admin/publish'
      preLoaderRoute: typeof ApiAdminPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password-verify-code': {
      id: '/api/admin/password-verify-code'
      path: '/api/admin/password-verify-code'
      fullPath: '/api/admin/password-verify-code'
      preLoaderRoute: typeof ApiAdminPasswordVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password-request-code': {
      id: '/api/admin/password-request-code'
      path: '/api/admin/password-request-code'
      fullPath: '/api/admin/password-request-code'
      preLoaderRoute: typeof ApiAdminPasswordRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/password-change': {
      id: '/api/admin/password-change'
      path: '/api/admin/password-change'
      fullPath: '/api/admin/password-change'
      preLoaderRoute: typeof ApiAdminPasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/menu-photo': {
      id: '/api/admin/menu-photo'
      path: '/api/admin/menu-photo'
      fullPath: '/api/admin/menu-photo'
      preLoaderRoute: typeof ApiAdminMenuPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/menu': {
      id: '/api/admin/menu'
      path: '/api/admin/menu'
      fullPath: '/api/admin/menu'
      preLoaderRoute: typeof ApiAdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-change-verify-code': {
      id: '/api/admin/email-change-verify-code'
      path: '/api/admin/email-change-verify-code'
      fullPath: '/api/admin/email-change-verify-code'
      preLoaderRoute: typeof ApiAdminEmailChangeVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-change-request-code': {
      id: '/api/admin/email-change-request-code'
      path: '/api/admin/email-change-request-code'
      fullPath: '/api/admin/email-change-request-code'
      preLoaderRoute: typeof ApiAdminEmailChangeRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-change': {
      id: '/api/admin/email-change'
      path: '/api/admin/email-change'
      fullPath: '/api/admin/email-change'
      preLoaderRoute: typeof ApiAdminEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiMenuRoute: ApiMenuRoute,
  ApiMenuImageRoute: ApiMenuImageRoute,
  ApiReviewImageRoute: ApiReviewImageRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRoute,
  ApiAdminEmailChangeRoute: ApiAdminEmailChangeRoute,
  ApiAdminEmailChangeRequestCodeRoute: ApiAdminEmailChangeRequestCodeRoute,
  ApiAdminEmailChangeVerifyCodeRoute: ApiAdminEmailChangeVerifyCodeRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminMenuRoute: ApiAdminMenuRoute,
  ApiAdminMenuPhotoRoute: ApiAdminMenuPhotoRoute,
  ApiAdminPasswordChangeRoute: ApiAdminPasswordChangeRoute,
  ApiAdminPasswordRequestCodeRoute: ApiAdminPasswordRequestCodeRoute,
  ApiAdminPasswordVerifyCodeRoute: ApiAdminPasswordVerifyCodeRoute,
  ApiAdminPublishRoute: ApiAdminPublishRoute,
  ApiAdminReviewPhotoRoute: ApiAdminReviewPhotoRoute,
  ApiAdminReviewSettingsRoute: ApiAdminReviewSettingsRoute,
  ApiAdminReviewsRoute: ApiAdminReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
