import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";
import { getAdmin, sameOrigin } from "../../../lib/admin-auth.server";
import { bindings } from "../../../lib/bindings.server";
const ReviewInput=z.object({id:z.string().regex(/^[A-Za-z0-9_-]+$/).max(80).optional(),reviewer_name:z.string().trim().min(1).max(80),rating:z.union([z.number().int().min(1).max(5),z.null()]),review_text:z.string().trim().min(1).max(1200),source:z.string().trim().max(80),published:z.boolean(),sort_order:z.number().int().min(0).max(9999)});
export const Route=createFileRoute("/api/admin/reviews")({server:{handlers:{
GET:async({request})=>{if(!await getAdmin(request))return Response.json({ok:false},{status:401});const {DB}=bindings();if(!DB)return Response.json({ok:false},{status:503});const reviews=await DB.prepare("SELECT id,reviewer_name,rating,review_text,image_key,source,published,sort_order,created_at,updated_at FROM reviews ORDER BY sort_order,id").all();const rows=await DB.prepare("SELECT key,value FROM site_settings WHERE key IN ('google_rating','google_review_count')").all();const settings=Object.fromEntries(rows.results.map(row=>[String((row as any).key),String((row as any).value)]));return Response.json({ok:true,reviews:reviews.results,settings},{headers:{"Cache-Control":"no-store"}});},
POST:async({request})=>{if(!sameOrigin(request))return Response.json({ok:false},{status:403});if(!await getAdmin(request))return Response.json({ok:false},{status:401});const {DB}=bindings();if(!DB)return Response.json({ok:false},{status:503});let input;try{input=ReviewInput.parse(await request.json());}catch{return Response.json({ok:false,code:"invalid_input"},{status:400});}const id=input.id||crypto.randomUUID();await DB.prepare("INSERT INTO reviews(id,reviewer_name,rating,review_text,source,published,sort_order,updated_at) VALUES(?,?,?,?,?,?,?,datetime('now')) ON CONFLICT(id) DO UPDATE SET reviewer_name=excluded.reviewer_name,rating=excluded.rating,review_text=excluded.review_text,source=excluded.source,published=excluded.published,sort_order=excluded.sort_order,updated_at=datetime('now')").bind(id,input.reviewer_name,input.rating,input.review_text,input.source,input.published?1:0,input.sort_order).run();return Response.json({ok:true,id});},
DELETE:async({request})=>{if(!sameOrigin(request))return Response.json({ok:false},{status:403});if(!await getAdmin(request))return Response.json({ok:false},{status:401});const id=new URL(request.url).searchParams.get("id")||"";if(!/^[A-Za-z0-9_-]+$/.test(id))return Response.json({ok:false},{status:400});const {DB}=bindings();if(!DB)return Response.json({ok:false},{status:503});await DB.prepare("DELETE FROM reviews WHERE id=?").bind(id).run();return Response.json({ok:true});}
}}});
